# Generated by Django 4.0.5 on 2022-07-03 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jpeg_main', models.ImageField(null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='WordLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('href', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FriendFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.friend')),
            ],
        ),
    ]
